In [1]:
#This notebook will be mainly used for the  project.
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import json # library to handle JSON files
#!conda install -c conda-forge geopy --yes # uncomment this line if you haven't completed the Foursquare API lab
from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

# import k-means from clustering stage
from sklearn.cluster import KMeans

#!conda install -c conda-forge folium=0.5.0 --yes # uncomment this line if you haven't completed the Foursquare API lab
import folium # map rendering library

In [79]:
df = pd.read_html('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M')[0]
#Loading data from Wikipedia
df.head()

Postal code           Borough                Neighborhood
0         M1A      Not assigned                         NaN
1         M2A      Not assigned                         NaN
2         M3A        North York                   Parkwoods
3         M4A        North York            Victoria Village
4         M5A  Downtown Toronto  Regent Park / Harbourfront

In [185]:
# filter data
df_filt = df[df['Borough'] != "Not assigned"] 
df_filt.isnull() #Check that there is no NaN by veiwing

Postal code  Borough  Neighborhood
2          False    False         False
3          False    False         False
4          False    False         False
5          False    False         False
6          False    False         False
8          False    False         False
9          False    False         False
11         False    False         False
12         False    False         False
13         False    False         False
14         False    False         False
17         False    False         False
18         False    False         False
20         False    False         False
21         False    False         False
22         False    False         False
23         False    False         False
26         False    False         False
27         False    False         False
30         False    False         False
31         False    False         False
32         False    False         False
36         False    False         False
39         False    False         False
40         False    False         False
41         False    False         False
45         False    False         False
46         False    False         False
47         False    False         False
48         False    False         False
49         False    False         False
50         False    False         False
54         False    False         False
55         False    False         False
56         False    False         False
57         False    False         False
58         False    False         False
59         False    False         False
63         False    False         False
64         False    False         False
65         False    False         False
66         False    False         False
67         False    False         False
68         False    False         False
72         False    False         False
73         False    False         False
74         False    False         False
75         False    False         False
76         False    False         False
77         False    False         False
80         False    False         False
81         False    False         False
82         False    False         False
83         False    False         False
84         False    False         False
85         False    False         False
86         False    False         False
89         False    False         False
90         False    False         False
91         False    False         False
92         False    False         False
93         False    False         False
94         False    False         False
95         False    False         False
98         False    False         False
99         False    False         False
100        False    False         False
102        False    False         False
103        False    False         False
104        False    False         False
107        False    False         False
108        False    False         False
109        False    False         False
111        False    False         False
112        False    False         False
113        False    False         False
114        False    False         False
116        False    False         False
117        False    False         False
120        False    False         False
121        False    False         False
122        False    False         False
126        False    False         False
129        False    False         False
130        False    False         False
135        False    False         False
138        False    False         False
139        False    False         False
142        False    False         False
143        False    False         False
144        False    False         False
147        False    False         False
148        False    False         False
151        False    False         False
152        False    False         False
153        False    False         False
156        False    False         False
157        False    False         False
160        False    False         False
165  

In [89]:
df2=df_filt[:]
df2.groupby('Postal code').count().sort_values(by=['Postal code', 'Borough', 'Neighborhood']).head()
# check that every Borough is unique

Borough  Neighborhood
Postal code                       
M1B                1             1
M1C                1             1
M1E                1             1
M1G                1             1
M1H                1             1

In [90]:
df2['Neighborhood'] = df2['Neighborhood'].str.replace(' /', ',') 
df2

Postal code           Borough  \
2           M3A        North York   
3           M4A        North York   
4           M5A  Downtown Toronto   
5           M6A        North York   
6           M7A  Downtown Toronto   
8           M9A         Etobicoke   
9           M1B       Scarborough   
11          M3B        North York   
12          M4B         East York   
13          M5B  Downtown Toronto   
14          M6B        North York   
17          M9B         Etobicoke   
18          M1C       Scarborough   
20          M3C        North York   
21          M4C         East York   
22          M5C  Downtown Toronto   
23          M6C              York   
26          M9C         Etobicoke   
27          M1E       Scarborough   
30          M4E      East Toronto   
31          M5E  Downtown Toronto   
32          M6E              York   
36          M1G       Scarborough   
39          M4G         East York   
40          M5G  Downtown Toronto   
41          M6G  Downtown Toronto   
45          M1H       Scarborough   
46          M2H        North York   
47          M3H        North York   
48          M4H         East York   
49          M5H  Downtown Toronto   
50          M6H      West Toronto   
54          M1J       Scarborough   
55          M2J        North York   
56          M3J        North York   
57          M4J         East York   
58          M5J  Downtown Toronto   
59          M6J      West Toronto   
63          M1K       Scarborough   
64          M2K        North York   
65          M3K        North York   
66          M4K      East Toronto   
67          M5K  Downtown Toronto   
68          M6K      West Toronto   
72          M1L       Scarborough   
73          M2L        North York   
74          M3L        North York   
75          M4L      East Toronto   
76          M5L  Downtown Toronto   
77          M6L        North York   
80          M9L        North York   
81          M1M       Scarborough   
82          M2M        North York   
83          M3M        North York   
84          M4M      East Toronto   
85          M5M        North York   
86          M6M              York   
89          M9M        North York   
90          M1N       Scarborough   
91          M2N        North York   
92          M3N        North York   
93          M4N   Central Toronto   
94          M5N   Central Toronto   
95          M6N              York   
98          M9N              York   
99          M1P       Scarborough   
100         M2P        North York   
102         M4P   Central Toronto   
103         M5P   Central Toronto   
104         M6P      West Toronto   
107         M9P         Etobicoke   
108         M1R       Scarborough   
109         M2R        North York   
111         M4R   Central Toronto   
112         M5R   Central Toronto   
113         M6R      West Toronto   
114         M7R       Mississauga   
116         M9R         Etobicoke   
117         M1S       Scarborough   
120         M4S   Central Toronto   
121         M5S  Downtown Toronto   
122         M6S      West Toronto   
126         M1T       Scarborough   
129         M4T   Central Toronto   
130         M5T  Downtown Toronto   
135         M1V       Scarborough   
138         M4V   Central Toronto   
139         M5V  Downtown Toronto   
142         M8V         Etobicoke   
143         M9V         Etobicoke   
144         M1W       Scarborough   
147         M4W  Downtown Toronto   
148         M5W  Downtown Toronto   
151         M8W         Etobicoke   
152         M9W         Etobicoke   
153         M1X       Scarborough   
156         M4X  Downtown Toronto   
157         M5X  Downtown Toronto   
160         M8X         Etobicoke   
165         M4Y  Downtown Toronto   
168         M7Y      East Toronto   
169         M8Y         Etobicoke   
178         M8Z         Etobicoke   

                                          Neighborhood  
2                                            Parkwoods  
3                                     Vic

In [190]:
df2=df2.reset_index(drop=True)
df2

Postal code           Borough  \
0           M3A        North York   
1           M4A        North York   
2           M5A  Downtown Toronto   
3           M6A        North York   
4           M7A  Downtown Toronto   
5           M9A         Etobicoke   
6           M1B       Scarborough   
7           M3B        North York   
8           M4B         East York   
9           M5B  Downtown Toronto   
10          M6B        North York   
11          M9B         Etobicoke   
12          M1C       Scarborough   
13          M3C        North York   
14          M4C         East York   
15          M5C  Downtown Toronto   
16          M6C              York   
17          M9C         Etobicoke   
18          M1E       Scarborough   
19          M4E      East Toronto   
20          M5E  Downtown Toronto   
21          M6E              York   
22          M1G       Scarborough   
23          M4G         East York   
24          M5G  Downtown Toronto   
25          M6G  Downtown Toronto   
26          M1H       Scarborough   
27          M2H        North York   
28          M3H        North York   
29          M4H         East York   
30          M5H  Downtown Toronto   
31          M6H      West Toronto   
32          M1J       Scarborough   
33          M2J        North York   
34          M3J        North York   
35          M4J         East York   
36          M5J  Downtown Toronto   
37          M6J      West Toronto   
38          M1K       Scarborough   
39          M2K        North York   
40          M3K        North York   
41          M4K      East Toronto   
42          M5K  Downtown Toronto   
43          M6K      West Toronto   
44          M1L       Scarborough   
45          M2L        North York   
46          M3L        North York   
47          M4L      East Toronto   
48          M5L  Downtown Toronto   
49          M6L        North York   
50          M9L        North York   
51          M1M       Scarborough   
52          M2M        North York   
53          M3M        North York   
54          M4M      East Toronto   
55          M5M        North York   
56          M6M              York   
57          M9M        North York   
58          M1N       Scarborough   
59          M2N        North York   
60          M3N        North York   
61          M4N   Central Toronto   
62          M5N   Central Toronto   
63          M6N              York   
64          M9N              York   
65          M1P       Scarborough   
66          M2P        North York   
67          M4P   Central Toronto   
68          M5P   Central Toronto   
69          M6P      West Toronto   
70          M9P         Etobicoke   
71          M1R       Scarborough   
72          M2R        North York   
73          M4R   Central Toronto   
74          M5R   Central Toronto   
75          M6R      West Toronto   
76          M7R       Mississauga   
77          M9R         Etobicoke   
78          M1S       Scarborough   
79          M4S   Central Toronto   
80          M5S  Downtown Toronto   
81          M6S      West Toronto   
82          M1T       Scarborough   
83          M4T   Central Toronto   
84          M5T  Downtown Toronto   
85          M1V       Scarborough   
86          M4V   Central Toronto   
87          M5V  Downtown Toronto   
88          M8V         Etobicoke   
89          M9V         Etobicoke   
90          M1W       Scarborough   
91          M4W  Downtown Toronto   
92          M5W  Downtown Toronto   
93          M8W         Etobicoke   
94          M9W         Etobicoke   
95          M1X       Scarborough   
96          M4X  Downtown Toronto   
97          M5X  Downtown Toronto   
98          M8X         Etobicoke   
99          M4Y  Downtown Toronto   
100         M7Y      East Toronto   
101         M8Y         Etobicoke   
102         M8Z         Etobicoke   

                                          Neighborhood  
0                                            Parkwoods  
1                                     Vic

In [191]:
# I downloaded the file above and loaded it
path='Geospatial_Coordinates.csv'
geop=pd.read_csv(path)
geop.head(2)

Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497

In [223]:
df4= df2.merge(geop, left_on='Postal code', right_on='Postal Code')
df4

Postal code           Borough  \
0           M3A        North York   
1           M4A        North York   
2           M5A  Downtown Toronto   
3           M6A        North York   
4           M7A  Downtown Toronto   
5           M9A         Etobicoke   
6           M1B       Scarborough   
7           M3B        North York   
8           M4B         East York   
9           M5B  Downtown Toronto   
10          M6B        North York   
11          M9B         Etobicoke   
12          M1C       Scarborough   
13          M3C        North York   
14          M4C         East York   
15          M5C  Downtown Toronto   
16          M6C              York   
17          M9C         Etobicoke   
18          M1E       Scarborough   
19          M4E      East Toronto   
20          M5E  Downtown Toronto   
21          M6E              York   
22          M1G       Scarborough   
23          M4G         East York   
24          M5G  Downtown Toronto   
25          M6G  Downtown Toronto   
26          M1H       Scarborough   
27          M2H        North York   
28          M3H        North York   
29          M4H         East York   
30          M5H  Downtown Toronto   
31          M6H      West Toronto   
32          M1J       Scarborough   
33          M2J        North York   
34          M3J        North York   
35          M4J         East York   
36          M5J  Downtown Toronto   
37          M6J      West Toronto   
38          M1K       Scarborough   
39          M2K        North York   
40          M3K        North York   
41          M4K      East Toronto   
42          M5K  Downtown Toronto   
43          M6K      West Toronto   
44          M1L       Scarborough   
45          M2L        North York   
46          M3L        North York   
47          M4L      East Toronto   
48          M5L  Downtown Toronto   
49          M6L        North York   
50          M9L        North York   
51          M1M       Scarborough   
52          M2M        North York   
53          M3M        North York   
54          M4M      East Toronto   
55          M5M        North York   
56          M6M              York   
57          M9M        North York   
58          M1N       Scarborough   
59          M2N        North York   
60          M3N        North York   
61          M4N   Central Toronto   
62          M5N   Central Toronto   
63          M6N              York   
64          M9N              York   
65          M1P       Scarborough   
66          M2P        North York   
67          M4P   Central Toronto   
68          M5P   Central Toronto   
69          M6P      West Toronto   
70          M9P         Etobicoke   
71          M1R       Scarborough   
72          M2R        North York   
73          M4R   Central Toronto   
74          M5R   Central Toronto   
75          M6R      West Toronto   
76          M7R       Mississauga   
77          M9R         Etobicoke   
78          M1S       Scarborough   
79          M4S   Central Toronto   
80          M5S  Downtown Toronto   
81          M6S      West Toronto   
82          M1T       Scarborough   
83          M4T   Central Toronto   
84          M5T  Downtown Toronto   
85          M1V       Scarborough   
86          M4V   Central Toronto   
87          M5V  Downtown Toronto   
88          M8V         Etobicoke   
89          M9V         Etobicoke   
90          M1W       Scarborough   
91          M4W  Downtown Toronto   
92          M5W  Downtown Toronto   
93          M8W         Etobicoke   
94          M9W         Etobicoke   
95          M1X       Scarborough   
96          M4X  Downtown Toronto   
97          M5X  Downtown Toronto   
98          M8X         Etobicoke   
99          M4Y  Downtown Toronto   
100         M7Y      East Toronto   
101         M8Y         Etobicoke   
102         M8Z         Etobicoke   

                                          Neighborhood Postal Code   Latitude  \
0                                            Parkwoods         M3A  43.753

In [224]:
#df4=df4.drop(['Postal Code'])
df4['tr2']=df4.apply(lambda x: 'Toronto' in x.Borough, axis=1)
df4=df4[df4['tr2']== 1]
df4=df4.drop(['tr2'], axis=1)

In [225]:
df4=df4.reset_index(drop=True)

In [226]:
address = 'Toronto, ON'

geolocator = Nominatim(user_agent="tor_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of Toronto are {}, {}.'.format(latitude, longitude))

The geograpical coordinate of Toronto are 43.6534817, -79.3839347.


In [228]:
CLIENT_ID = 'K3W0ZZJYCSGML0I4CCFDRJCQ0CZFSPIAAWGMUE0WZ453PXZC' #  Foursquare ID
CLIENT_SECRET = 'YXDSD0X0341OF2HRC4YPW4DS4WOWWIWEUADZRSR4J0TDU4IV' #  Foursquare Secret
VERSION = '20180605' # Foursquare API version

LIMIT=100

In [229]:
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [230]:

toronto_venues = getNearbyVenues(names=df4['Neighborhood'],
                                   latitudes=df4['Latitude'],
                                   longitudes=df4['Longitude']
                                  )

Regent Park, Harbourfront
Queen's Park, Ontario Provincial Government
Garden District, Ryerson
St. James Town
The Beaches
Berczy Park
Central Bay Street
Christie
Richmond, Adelaide, King
Dufferin, Dovercourt Village
Harbourfront East, Union Station, Toronto Islands
Little Portugal, Trinity
The Danforth West, Riverdale
Toronto Dominion Centre, Design Exchange
Brockton, Parkdale Village, Exhibition Place
India Bazaar, The Beaches West
Commerce Court, Victoria Hotel
Studio District
Lawrence Park
Roselawn
Davisville North
Forest Hill North & West
High Park, The Junction South
North Toronto West
The Annex, North Midtown, Yorkville
Parkdale, Roncesvalles
Davisville
University of Toronto, Harbord
Runnymede, Swansea
Moore Park, Summerhill East
Kensington Market, Chinatown, Grange Park
Summerhill West, Rathnelly, South Hill, Forest Hill SE, Deer Park
CN Tower, King and Spadina, Railway Lands, Harbourfront West, Bathurst Quay, South Niagara, Island airport
Rosedale
Stn A PO Boxes
St. James Town,

In [231]:

toronto_venues.groupby('Neighborhood').count()

Neighborhood Latitude  \
Neighborhood                                                                
Berczy Park                                                            58   
Brockton, Parkdale Village, Exhibition Place                           23   
Business reply mail Processing CentrE                                  15   
CN Tower, King and Spadina, Railway Lands, Harb...                     14   
Central Bay Street                                                     62   
Christie                                                               18   
Church and Wellesley                                                   74   
Commerce Court, Victoria Hotel                                        100   
Davisville                                                             39   
Davisville North                                                        7   
Dufferin, Dovercourt Village                                           15   
First Canadian Place, Underground city                                100   
Forest Hill North & West                                                4   
Garden District, Ryerson                                              100   
Harbourfront East, Union Station, Toronto Islands                     100   
High Park, The Junction South                                          23   
India Bazaar, The Beaches West                                         17   
Kensington Market, Chinatown, Grange Park                              57   
Lawrence Park                                                           4   
Little Portugal, Trinity                                               41   
Moore Park, Summerhill East                                             3   
North Toronto West                                                     21   
Parkdale, Roncesvalles                                                 13   
Queen's Park, Ontario Provincial Government                            40   
Regent Park, Harbourfront                                              48   
Richmond, Adelaide, King                                               95   
Rosedale                                                                4   
Roselawn                                                                2   
Runnymede, Swansea                                                     40   
St. James Town                                                         82   
St. James Town, Cabbagetown                                            41   
Stn A PO Boxes                                                         97   
Studio District                                                        40   
Summerhill West, Rathnelly, South Hill, Forest ...                     16   
The Annex, North Midtown, Yorkville                                    23   
The Beaches                                                             4   
The Danforth West, Riverdale                                           43   
Toronto Dominion Centre, Design Exchange                              100   
University of Toronto, Harbord                                         35   

                                                    Neighborhood Longitude  \
Neighborhood                                                                 
Berczy Park                                                             58   
Brockton, Parkdale Village, Exhibition Place                            23   
Business reply mail Processing CentrE                                   15   
CN Tower, King and Spadina, Railway Lands, Harb...                      14   
Central Bay Street                                                      62   
Christie                                                                18   
Church and Wellesley                                                    74   
Commerce Court, Victoria Hotel                                         100   
Davisville                                                              39   
Davisville North                    

In [232]:
print('There are {} uniques categories.'.format(len(toronto_venues['Venue Category'].unique())))

There are 233 uniques categories.


In [233]:
# one hot encoding
toronto_onehot = pd.get_dummies(toronto_venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
toronto_onehot['Neighborhood'] = toronto_venues['Neighborhood'] 

# move neighborhood column to the first column
fixed_columns = [toronto_onehot.columns[-1]] + list(toronto_onehot.columns[:-1])
toronto_onehot = toronto_onehot[fixed_columns]

toronto_onehot.head()

Yoga Studio  Airport  Airport Food Court  Airport Lounge  Airport Service  \
0            0        0                   0               0                0   
1            0        0                   0               0                0   
2            0        0                   0               0                0   
3            0        0                   0               0                0   
4            0        0                   0               0                0   

   Airport Terminal  American Restaurant  Antique Shop  Aquarium  Art Gallery  \
0                 0                    0             0         0            0   
1                 0                    0             0         0            0   
2                 0                    0             0         0            0   
3                 0                    0             0         0            0   
4                 0                    0             0         0            0   

   Art Museum  Arts & Crafts Store  Asian Restaurant  Athletics & Sports  \
0           0                    0                 0                   0   
1           0                    0                 0                   0   
2           0                    0                 0                   0   
3           0                    0                 0                   0   
4           0                    0                 0                   0   

   Auto Workshop  BBQ Joint  Baby Store  Bagel Shop  Bakery  Bank  Bar  \
0              0          0           0           0       1     0    0   
1              0          0           0           0       0     0    0   
2              0          0           0           0       0     0    0   
3              0          0           0           0       0     0    0   
4              0          0           0           0       0     0    0   

   Baseball Stadium  Basketball Stadium  Beach  Bed & Breakfast  Beer Bar  \
0                 0                   0      0                0         0   
1                 0                   0      0                0         0   
2                 0                   0      0                0         0   
3                 0                   0      0                0         0   
4                 0                   0      0                0         0   

   Beer Store  Belgian Restaurant  Bistro  Boat or Ferry  Bookstore  Boutique  \
0           0                   0       0              0          0         0   
1           0                   0       0              0          0         0   
2           0                   0       0              0          0         0   
3           0                   0       0              0          0         0   
4           0                   0       0              0          0         0   

   Brazilian Restaurant  Breakfast Spot  Brewery  Bubble Tea Shop  Building  \
0                     0               0        0                0         0   
1                     0               0        0                0         0   
2                     0               1        0                0         0   
3                     0               0        0                0         0   
4                     0               0        0                0         0   

   Burger Joint  Burrito Place  Bus Line  Butcher  Café  \
0             0              0         0        0     0   
1             0              0         0        0     0   
2             0              0         0        0     0   
3             0              0         0        0     0   
4             0              0         0        0     0   

   Cajun / Creole Restaurant  Candy Store  Caribbean Restaurant  Cheese Shop  \
0                          0            0                     0            0   
1                          0            0                     0            0   
2                          0            0                     0            0   
3                          0     

In [234]:
toronto_grouped = toronto_onehot.groupby('Neighborhood').mean().reset_index()
toronto_grouped

Neighborhood  Yoga Studio   Airport  \
0                                         Berczy Park     0.000000  0.000000   
1        Brockton, Parkdale Village, Exhibition Place     0.000000  0.000000   
2               Business reply mail Processing CentrE     0.000000  0.000000   
3   CN Tower, King and Spadina, Railway Lands, Har...     0.000000  0.071429   
4                                  Central Bay Street     0.016129  0.000000   
5                                            Christie     0.000000  0.000000   
6                                Church and Wellesley     0.027027  0.000000   
7                      Commerce Court, Victoria Hotel     0.000000  0.000000   
8                                          Davisville     0.000000  0.000000   
9                                    Davisville North     0.000000  0.000000   
10                       Dufferin, Dovercourt Village     0.000000  0.000000   
11             First Canadian Place, Underground city     0.000000  0.000000   
12                           Forest Hill North & West     0.000000  0.000000   
13                           Garden District, Ryerson     0.000000  0.000000   
14  Harbourfront East, Union Station, Toronto Islands     0.000000  0.000000   
15                      High Park, The Junction South     0.000000  0.000000   
16                     India Bazaar, The Beaches West     0.000000  0.000000   
17          Kensington Market, Chinatown, Grange Park     0.000000  0.000000   
18                                      Lawrence Park     0.000000  0.000000   
19                           Little Portugal, Trinity     0.024390  0.000000   
20                        Moore Park, Summerhill East     0.000000  0.000000   
21                                 North Toronto West     0.047619  0.000000   
22                             Parkdale, Roncesvalles     0.000000  0.000000   
23        Queen's Park, Ontario Provincial Government     0.025000  0.000000   
24                          Regent Park, Harbourfront     0.020833  0.000000   
25                           Richmond, Adelaide, King     0.000000  0.000000   
26                                           Rosedale     0.000000  0.000000   
27                                           Roselawn     0.000000  0.000000   
28                                 Runnymede, Swansea     0.000000  0.000000   
29                                     St. James Town     0.000000  0.000000   
30                        St. James Town, Cabbagetown     0.000000  0.000000   
31                                     Stn A PO Boxes     0.010309  0.000000   
32                                    Studio District     0.025000  0.000000   
33  Summerhill West, Rathnelly, South Hill, Forest...     0.000000  0.000000   
34                The Annex, North Midtown, Yorkville     0.000000  0.000000   
35                                        The Beaches     0.000000  0.000000   
36                       The Danforth West, Riverdale     0.023256  0.000000   
37           Toronto Dominion Centre, Design Exchange     0.000000  0.000000   
38                     University of Toronto, Harbord     0.028571  0.000000   

    Airport Food Court  Airport Lounge  Airport Service  Airport Terminal  \
0             0.000000        0.000000         0.000000          0.000000   
1             0.000000        0.000000         0.000000          0.000000   
2             0.000000        0.000000         0.000000          0.000000   
3             0.071429        0.142857         0.142857          0.142857   
4             0.000000        0.000000         0.000000          0.000000   
5             0.000000        0.000000         0.000000          0.000000   
6             0.000000        0.000000         0.000000          0.000000   
7             0.000000        0.000000         0.000000          0.000000   
8             0.000000        0.000000         0.000000          0.000000   
9             0.000000        0.000000         0.000000          0.000

In [235]:
num_top_venues = 5

for hood in toronto_grouped['Neighborhood']:
    print("----"+hood+"----")
    temp = toronto_grouped[toronto_grouped['Neighborhood'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

----Berczy Park----
            venue  freq
0     Coffee Shop  0.07
1    Cocktail Bar  0.05
2  Farmers Market  0.03
3      Restaurant  0.03
4        Beer Bar  0.03


----Brockton, Parkdale Village, Exhibition Place----
            venue  freq
0            Café  0.13
1  Breakfast Spot  0.09
2     Coffee Shop  0.09
3       Nightclub  0.09
4          Bakery  0.04


----Business reply mail Processing CentrE----
              venue  freq
0        Comic Shop  0.07
1     Auto Workshop  0.07
2  Recording Studio  0.07
3        Restaurant  0.07
4           Butcher  0.07


----CN Tower, King and Spadina, Railway Lands, Harbourfront West, Bathurst Quay, South Niagara, Island airport----
              venue  freq
0    Airport Lounge  0.14
1   Airport Service  0.14
2  Airport Terminal  0.14
3             Plane  0.07
4   Harbor / Marina  0.07


----Central Bay Street----
                venue  freq
0         Coffee Shop  0.21
1                Café  0.08
2  Italian Restaurant  0.06
3      Sandwich Pla

In [236]:
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

In [269]:
num_top_venues = 5

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Neighborhood']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
neighborhoods_venues_sorted = pd.DataFrame(columns=columns)
neighborhoods_venues_sorted['Neighborhood'] = toronto_grouped['Neighborhood']

for ind in np.arange(toronto_grouped.shape[0]):
    neighborhoods_venues_sorted.iloc[ind, 1:] = return_most_common_venues(toronto_grouped.iloc[ind, :], num_top_venues)

neighborhoods_venues_sorted.head()

Neighborhood 1st Most Common Venue  \
0                                        Berczy Park           Coffee Shop   
1       Brockton, Parkdale Village, Exhibition Place                  Café   
2              Business reply mail Processing CentrE            Skate Park   
3  CN Tower, King and Spadina, Railway Lands, Har...        Airport Lounge   
4                                 Central Bay Street           Coffee Shop   

  2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
0          Cocktail Bar    Italian Restaurant              Beer Bar   
1           Coffee Shop             Nightclub        Breakfast Spot   
2      Recording Studio            Restaurant    Light Rail Station   
3       Airport Service      Airport Terminal              Boutique   
4                  Café    Italian Restaurant        Sandwich Place   

   5th Most Common Venue  
0             Restaurant  
1  Performing Arts Venue  
2                Butcher  
3        Harbor / Marina  
4            Salad Place

In [270]:
kclusters = 5

toronto_grouped_clustering = toronto_grouped.drop('Neighborhood', 1)
print(toronto_grouped_clustering)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(toronto_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_

    Yoga Studio   Airport  Airport Food Court  Airport Lounge  \
0      0.000000  0.000000            0.000000        0.000000   
1      0.000000  0.000000            0.000000        0.000000   
2      0.000000  0.000000            0.000000        0.000000   
3      0.000000  0.071429            0.071429        0.142857   
4      0.016129  0.000000            0.000000        0.000000   
5      0.000000  0.000000            0.000000        0.000000   
6      0.027027  0.000000            0.000000        0.000000   
7      0.000000  0.000000            0.000000        0.000000   
8      0.000000  0.000000            0.000000        0.000000   
9      0.000000  0.000000            0.000000        0.000000   
10     0.000000  0.000000            0.000000        0.000000   
11     0.000000  0.000000            0.000000        0.000000   
12     0.000000  0.000000            0.000000        0.000000   
13     0.000000  0.000000            0.000000        0.000000   
14     0.000000  0.000000

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 4, 0,
       0, 0, 0, 0, 4, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [271]:
#df4=df4.reset_index()

#df4=df4.drop(['index', 'level_0'], axis=1)
neighborhoods_venues_sorted

Neighborhood 1st Most Common Venue  \
0                                         Berczy Park           Coffee Shop   
1        Brockton, Parkdale Village, Exhibition Place                  Café   
2               Business reply mail Processing CentrE            Skate Park   
3   CN Tower, King and Spadina, Railway Lands, Har...        Airport Lounge   
4                                  Central Bay Street           Coffee Shop   
5                                            Christie         Grocery Store   
6                                Church and Wellesley      Sushi Restaurant   
7                      Commerce Court, Victoria Hotel           Coffee Shop   
8                                          Davisville        Sandwich Place   
9                                    Davisville North                  Park   
10                       Dufferin, Dovercourt Village                Bakery   
11             First Canadian Place, Underground city           Coffee Shop   
12                           Forest Hill North & West         Jewelry Store   
13                           Garden District, Ryerson        Clothing Store   
14  Harbourfront East, Union Station, Toronto Islands           Coffee Shop   
15                      High Park, The Junction South                  Café   
16                     India Bazaar, The Beaches West  Fast Food Restaurant   
17          Kensington Market, Chinatown, Grange Park                  Café   
18                                      Lawrence Park                  Park   
19                           Little Portugal, Trinity                   Bar   
20                        Moore Park, Summerhill East                  Park   
21                                 North Toronto West        Clothing Store   
22                             Parkdale, Roncesvalles             Gift Shop   
23        Queen's Park, Ontario Provincial Government           Coffee Shop   
24                          Regent Park, Harbourfront           Coffee Shop   
25                           Richmond, Adelaide, King           Coffee Shop   
26                                           Rosedale                  Park   
27                                           Roselawn                Garden   
28                                 Runnymede, Swansea           Coffee Shop   
29                                     St. James Town           Coffee Shop   
30                        St. James Town, Cabbagetown           Coffee Shop   
31                                     Stn A PO Boxes           Coffee Shop   
32                                    Studio District                  Café   
33  Summerhill West, Rathnelly, South Hill, Forest...           Coffee Shop   
34                The Annex, North Midtown, Yorkville                  Café   
35                                        The Beaches                 Trail   
36                       The Danforth West, Riverdale      Greek Restaurant   
37           Toronto Dominion Centre, Design Exchange           Coffee Shop   
38                     University of Toronto, Harbord                  Café   

   2nd Most Common Venue 3rd Most Common Venue   4th Most Common Venue  \
0           Cocktail Bar    Italian Restaurant                Beer Bar   
1            Coffee Shop             Nightclub          Breakfast Spot   
2       Recording Studio            Restaurant      Light Rail Station   
3        Airport Service      Airport Terminal                Boutique   
4                   Café    Italian Restaurant          Sandwich Place   
5                   Café                  Park             Coffee Shop   
6    Japanese Restaurant           Coffee Shop              Restaurant   
7             Restaurant                  Café                   Hotel   
8           Dessert Shop           Pizza Place             Coffee Shop   
9       Department Store        Breakfast Spot          Sandwich Place   
10              Pharmacy                   Bar                    

In [272]:


# add clustering labels
neighborhoods_venues_sorted.insert(0, 'Cluster Labels', kmeans.labels_)
print(neighborhoods_venues_sorted)
toronto_merged = df4[:]

# merge toronto_grouped with toronto_data to add latitude/longitude for each neighborhood
toronto_merged = toronto_merged.join(neighborhoods_venues_sorted.set_index('Neighborhood'), on='Neighborhood')
toronto_merged['Cluster Labels']=toronto_merged2['Cluster Labels'].astype(int)
toronto_merged.head() # check the last columns!


    Cluster Labels                                       Neighborhood  \
0                0                                        Berczy Park   
1                0       Brockton, Parkdale Village, Exhibition Place   
2                0              Business reply mail Processing CentrE   
3                1  CN Tower, King and Spadina, Railway Lands, Har...   
4                0                                 Central Bay Street   
5                0                                           Christie   
6                0                               Church and Wellesley   
7                0                     Commerce Court, Victoria Hotel   
8                0                                         Davisville   
9                0                                   Davisville North   
10               0                       Dufferin, Dovercourt Village   
11               0             First Canadian Place, Underground city   
12               3                           Forest

NameError: name 'toronto_merged2' is not defined

In [274]:
# create map
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
print(x)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
print(colors_array)
#colors_array=colors_array.astype(int)
print(colors_array)

rainbow = [colors.rgb2hex(i) for i in colors_array]
print(rainbow)
# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(toronto_merged['Latitude'], toronto_merged['Longitude'],toronto_merged['Neighborhood'], toronto_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[int(cluster)-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

[0 1 2 3 4]
[[5.00000000e-01 0.00000000e+00 1.00000000e+00 1.00000000e+00]
 [1.96078431e-03 7.09281308e-01 9.23289106e-01 1.00000000e+00]
 [5.03921569e-01 9.99981027e-01 7.04925547e-01 1.00000000e+00]
 [1.00000000e+00 7.00543038e-01 3.78411050e-01 1.00000000e+00]
 [1.00000000e+00 1.22464680e-16 6.12323400e-17 1.00000000e+00]]
[[5.00000000e-01 0.00000000e+00 1.00000000e+00 1.00000000e+00]
 [1.96078431e-03 7.09281308e-01 9.23289106e-01 1.00000000e+00]
 [5.03921569e-01 9.99981027e-01 7.04925547e-01 1.00000000e+00]
 [1.00000000e+00 7.00543038e-01 3.78411050e-01 1.00000000e+00]
 [1.00000000e+00 1.22464680e-16 6.12323400e-17 1.00000000e+00]]
['#8000ff', '#00b5eb', '#80ffb4', '#ffb360', '#ff0000']


In [275]:
#Cluster with Coffee Shop Common Venue
toronto_merged.loc[toronto_merged['Cluster Labels'] == 0, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough  Longitude  Cluster Labels 1st Most Common Venue  \
0   Downtown Toronto -79.360636               0           Coffee Shop   
1   Downtown Toronto -79.389494               0           Coffee Shop   
2   Downtown Toronto -79.378937               0        Clothing Store   
3   Downtown Toronto -79.375418               0           Coffee Shop   
4       East Toronto -79.293031               0                 Trail   
5   Downtown Toronto -79.373306               0           Coffee Shop   
6   Downtown Toronto -79.387383               0           Coffee Shop   
7   Downtown Toronto -79.422564               0         Grocery Store   
8   Downtown Toronto -79.384568               0           Coffee Shop   
9       West Toronto -79.442259               0                Bakery   
10  Downtown Toronto -79.381752               0           Coffee Shop   
11      West Toronto -79.419750               0                   Bar   
12      East Toronto -79.352188               0      Greek Restaurant   
13  Downtown Toronto -79.381576               0           Coffee Shop   
14      West Toronto -79.428191               0                  Café   
15      East Toronto -79.315572               0  Fast Food Restaurant   
16  Downtown Toronto -79.379817               0           Coffee Shop   
17      East Toronto -79.340923               0                  Café   
18   Central Toronto -79.388790               0                  Park   
20   Central Toronto -79.390197               0                  Park   
22      West Toronto -79.464763               0                  Café   
23   Central Toronto -79.405678               0        Clothing Store   
24   Central Toronto -79.405678               0                  Café   
25      West Toronto -79.456325               0             Gift Shop   
26   Central Toronto -79.388790               0        Sandwich Place   
27  Downtown Toronto -79.400049               0                  Café   
28      West Toronto -79.484450               0           Coffee Shop   
30  Downtown Toronto -79.400049               0                  Café   
31   Central Toronto -79.400049               0           Coffee Shop   
34  Downtown Toronto -79.374846               0           Coffee Shop   
35  Downtown Toronto -79.367675               0           Coffee Shop   
36  Downtown Toronto -79.382280               0           Coffee Shop   
37  Downtown Toronto -79.383160               0      Sushi Restaurant   
38      East Toronto -79.321558               0            Skate Park   

   2nd Most Common Venue 3rd Most Common Venue   4th Most Common Venue  \
0                   Park                   Pub                  Bakery   
1       Sushi Restaurant                 Diner             Yoga Studio   
2            Coffee Shop                  Café              Restaurant   
3                   Café             Gastropub      Italian Restaurant   
4      Health Food Store                   Pub           Women's Store   
5           Cocktail Bar    Italian Restaurant                Beer Bar   
6                   Café    Italian Restaurant          Sandwich Place   
7                   Café                  Park             Coffee Shop   
8                   Café            Restaurant          Clothing Store   
9               Pharmacy                   Bar                    Bank   
10              Aquarium                  Café                   Hotel   
11            Restaurant           Men's Store        Asian Restaurant   
12           Coffee Shop    Italian Restaurant  Furniture / Home Store   
13                 Hotel                  Café     Japanese Restaurant   
14           Coffee Shop             Nightclub          Breakfast Spot   
15                  Park                   Pub          Sandwich Place   
16            Restaurant                  Café                   Hotel   
17           Coffee Shop             Gastropub                  Bakery   
18              Bus Line    Dim Sum Restaurant     

In [276]:
# CLuster of Neaborhoods with Airoport Common Venue
toronto_merged.loc[toronto_merged['Cluster Labels'] == 1,toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough  Longitude  Cluster Labels 1st Most Common Venue  \
32  Downtown Toronto  -79.39442               1        Airport Lounge   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
32       Airport Service      Airport Terminal              Boutique   

   5th Most Common Venue  
32       Harbor / Marina

In [277]:
# Cluster with Garden Common Venue
toronto_merged.loc[toronto_merged['Cluster Labels'] == 2,toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough  Longitude  Cluster Labels 1st Most Common Venue  \
19  Central Toronto -79.416936               2                Garden   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
19           Music Venue         Women's Store         Deli / Bodega   

          5th Most Common Venue  
19  Eastern European Restaurant

In [278]:
# Cluster with Jewelry Store Common Venue
toronto_merged.loc[toronto_merged['Cluster Labels'] == 3,toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough  Longitude  Cluster Labels 1st Most Common Venue  \
21  Central Toronto -79.411307               3         Jewelry Store   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
21                 Trail    Mexican Restaurant      Sushi Restaurant   

   5th Most Common Venue  
21         Women's Store

In [279]:
# Cluster with Park and Playground  Common Venue 
toronto_merged.loc[toronto_merged['Cluster Labels'] == 4,toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough  Longitude  Cluster Labels 1st Most Common Venue  \
29   Central Toronto -79.383160               4                  Park   
33  Downtown Toronto -79.377529               4                  Park   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
29            Playground                 Trail          Dance Studio   
33            Playground                 Trail          Dance Studio   

          5th Most Common Venue  
29  Eastern European Restaurant  
33  Eastern European Restaurant